# Generated by Django 2.2.3 on 2019-08-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_fair', '0002_auto_20190804_1640'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
    ]
