# Generated by Django 2.2.3 on 2019-08-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_fair', '0003_auto_20190804_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
