# Generated by Django 2.2.3 on 2019-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_fair', '0004_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
    ]
