# Generated by Django 2.2.3 on 2019-08-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_fair', '0006_faq_answer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQs'},
        ),
    ]
